AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Sets up Budget that creates OpsItem when forecasted budget exceeds 105% previous three months average

Resources:
  BudgetAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:opsitem:3#CATEGORY=Cost # severity 3 (~medium) should suffice
      AlarmDescription: Superwerker default budget forecast exceed previous three months
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: TopicName
          Value: !GetAtt BudgetNotification.TopicName
      EvaluationPeriods: 1
      MetricName: NumberOfMessagesPublished
      Namespace: AWS/SNS
      Period: 300 # publishing window of SNS metrics to CW
      Statistic: Sum
      Threshold: 0
      TreatMissingData: missing # currently CW does not auto close ops items where it's alert transitions back to OK - but still transition back after one (1) initial SNS notification from budgets to "Ok" would communicate wrong semantics;

  BudgetNotification:
    Type: AWS::SNS::Topic

  BudgetNotificationPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
          Action: SNS:Publish
          Effect: Allow
          Principal:
            Service: budgets.amazonaws.com
          Resource: !Ref BudgetNotification
      Topics:
        - !Ref BudgetNotification

  BudgetReport:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetType: COST
        CostTypes:
          IncludeCredit: false
          IncludeRefund: false
        TimeUnit: MONTHLY
        AutoAdjustData:
          AutoAdjustType: HISTORICAL
          HistoricalOptions:
              BudgetAdjustmentPeriod: 3
      NotificationsWithSubscribers:
        - Notification:
            ComparisonOperator: GREATER_THAN
            NotificationType: FORECASTED
            Threshold: 105
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref BudgetNotification