homeRegion: &HOME_REGION {{REGION}}
enabledRegions:
  - *HOME_REGION
managementAccountAccessRole: AWSControlTowerExecution
cloudwatchLogRetentionInDays: 365 # REDUCED FROM 3653
snsTopics:
  deploymentTargets:
    accounts:
      - Management
  topics:
    - name: Security
      emailAddresses:
        - {{AUDIT_MAIL}} # TODO: auto subscribe to Accelerator Security Topic
cdkOptions:
  centralizeBuckets: true
  useManagementAccessRole: true
terminationProtection: true
controlTower:
  enable: true
  controls: []
logging:
  account: LogArchive
  cloudtrail:
    enable: false
    organizationTrail: false
    organizationTrailSettings:
      multiRegionTrail: true
      globalServiceEvents: true
      managementEvents: true
      s3DataEvents: true
      lambdaDataEvents: true
      sendToCloudWatchLogs: true
      apiErrorRateInsight: false
      apiCallRateInsight: false
    accountTrails: []
    lifecycleRules: []
  sessionManager:
    sendToCloudWatchLogs: false
    sendToS3: true
    lifecycleRules:
      - enabled: true
        abortIncompleteMultipartUpload: 7
        expiration: 30
        noncurrentVersionExpiration: 30
    attachPolicyToIamRoles:
      - EC2-Sessions-Manager-Role
tags: []
iamRoleSsmParameters: []
