name: CDK release

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.RELEASES_AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.RELEASES_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      id: semantic
      with:
        extra_plugins: |
          @semantic-release/git
          @semantic-release/changelog
        branches: |
          ['v+([0-9])?(.{+([0-9]),x}).x', 'main', {name: 'cdk', prerelease: true}]
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: cdk release
      if: steps.semantic.outputs.new_release_published == 'true'
      run: |
        pip install cfn-flip
        yarn
        yarn test
        yarn synth
        yarn publish-assets
        cfn-flip cdk.out/SuperwerkerStack.template.json cdk.out/superwerker.template.yaml
        aws s3 cp cdk.out/superwerker.template.yaml s3://superwerker-releases/${SUPERWERKER_VERSION}/templates/
        aws s3 cp cdk.out/SuperwerkerStack.template.json s3://superwerker-releases/${SUPERWERKER_VERSION}/templates/
      env:
        SUPERWERKER_VERSION: ${{ steps.semantic.outputs.new_release_version }}
      shell: bash
      working-directory: cdk

